export const SORT_TYPE = {
  PRICE_HIGH_TO_LOW: 'priceHighToLow',
  PRICE_LOW_TO_HIGH: 'priceLowToHigh',
  RATING_HIGH_TO_LOW: 'ratingHighToLow',
}

export const RATING_TYPE = {
  FOUR_AND_UP: '4',
  THREE_AND_UP: '3',
  TWO_AND_UP: '2',
  ONE_AND_UP: '1',
}

export const RATING_ITEMS = [
  { value: RATING_TYPE.FOUR_AND_UP, label: '4★ & above' },
  { value: RATING_TYPE.THREE_AND_UP, label: '3★ & above' },
  { value: RATING_TYPE.TWO_AND_UP, label: '2★ & above' },
  { value: RATING_TYPE.ONE_AND_UP, label: '1★ & above' },
]

export const SORT_ITEMS = [
  { value: SORT_TYPE.PRICE_HIGH_TO_LOW, label: 'Price high to low' },
  { value: SORT_TYPE.PRICE_LOW_TO_HIGH, label: 'Price low to high' },
  { value: SORT_TYPE.RATING_HIGH_TO_LOW, label: 'Rating High To Low' },
]

type CategoryType = Record<string, string>

export const CATEGORIES: CategoryType = {
  Smartphones: 'smartphones',
  Laptops: 'laptops',
  Fragrances: 'fragrances',
  Skincare: 'skincare',
  Groceries: 'groceries',
  'Home Decoration': 'home-decoration',
  Furniture: 'furniture',
  Tops: 'tops',
  'Womens Dresses': 'womens-dresses',
  'Womens Shoes': 'womens-shoes',
  'Mens Shirts': 'mens-shirts',
  'Mens Shoes': 'mens-shoes',
  'Mens Watches': 'mens-watches',
  'Womens Watches': 'womens-watches',
  'Womens Bags': 'womens-bags',
  'Womens Jewellery': 'womens-jewellery',
  Sunglasses: 'sunglasses',
  Automotive: 'automotive',
  Motorcycle: 'motorcycle',
  Lighting: 'lighting',
}

export const BRAND = [
  'Apple',
  'Samsung',
  'OPPO',
  'Huawei',
  'Microsoft Surface',
  'Infinix',
  'HP Pavilion',
  'Impression of Acqua Di Gio',
  'Royal_Mirage',
  'Fog Scent Xpressio',
  'Al Munakh',
  'Lord - Al-Rehab',
  "L'Oreal Paris",
  'Hemani Tea',
  'Dermive',
  'ROREC White Rice',
  'Fair & Clear',
  'Saaf & Khaas',
  'Bake Parlor Big',
  'Baking Food Items',
  'fauji',
  'Dry Rose',
  'Boho Decor',
  'Flying Wooden',
  'LED Lights',
  'luxury palace',
  'Golden',
  'Furniture Bed Set',
  'Ratttan Outdoor',
  'Kitchen Shelf',
  'Multi Purpose',
  'AmnaMart',
  'Professional Wear',
  'Soft Cotton',
  'Top Sweater',
  'RED MICKY MOUSE..',
  'Digital Printed',
  'Ghazi Fabric',
  'IELGY',
  'IELGY fashion',
  'Synthetic Leather',
  'Sandals Flip Flops',
  'Maasai Sandals',
  'Arrivals Genuine',
  'Vintage Apparel',
  'FREE FIRE',
  'The Warehouse',
  'Sneakers',
  'Rubber',
  'Naviforce',
  'SKMEI 9117',
  'Strap Skeleton',
  'Stainless',
  'Eastern Watches',
  'Luxury Digital',
  'Watch Pearls',
  'Bracelet',
  'LouisWill',
  'Copenhagen Luxe',
  'Steal Frame',
  'Darojay',
  'Fashion Jewellery',
  'Cuff Butterfly',
  'Designer Sun Glasses',
  'mastar watch',
  'Car Aux',
  'W1209 DC12V',
  'TC Reusable',
  'Neon LED Light',
  'METRO 70cc Motorcycle - MR70',
  'BRAVE BULL',
  'shock absorber',
  'JIEPOLLY',
  'Xiangle',
  'lightingbrilliance',
  'Ifei Home',
  'DADAWU',
  'YIOSI',
]
